### ISSUE TITLE
-c 옵션을 다른 옵션과 섞어 섰을 때 오류

### ISSUE THREAD

**Issue by weongyo** [truefinder/tonbi#10]
```
$ cat ~/Downloads/tonbi/config.json
{
        "head_count" : 5,
        "tail_count" : 5,
        "plugins" : [ "" ],
        "ignore_files" :  [ "jpg", "png", "jpeg", "ico", "gif", "tif" , "tiff", "bmp", ".po" ] ,
        "ignore_dirs" : [ ".git", "node_modules"]
}
$ python3 ~/Downloads/tonbi/tonbi.py -c ~/Downloads/tonbi/config.json -d src -p flask -l python --exclude=sql_injection1 --exclude=sql_injection_var --exclude=sql_injection_raw
load config setting 
Traceback (most recent call last):
  File "/home/weongyo/Downloads/tonbi/tonbi.py", line 555, in <module>
    main()
  File "/home/weongyo/Downloads/tonbi/tonbi.py", line 498, in main
    load_config()
  File "/home/weongyo/Downloads/tonbi/tonbi.py", line 136, in load_config
    config.source_directory = config_dic["source_directory"] 
KeyError: 'source_directory'
```
설정 파일을 위와 같이 구성하고, 아래의 명령처럼 실행하면 오류가 납니다.

**Comment by truefinder** [comment]
아이구... 설정화일 넣으면 설정화일 안에 내용만 보고, ci의 다른 옵션 다 무시되는데... 
이럴땐 어케 하면 좋아 -_-?

**Comment by truefinder** [comment]
고쳐진거 같은데 ?

**Comment by weongyo** [comment]
이번엔 다른 이슈가 나네요.  if ('source_directory' in config_dic) 같은 문법이 들어가야 할 것 같아요.

```
$ python3 ~/Downloads/tonbi/tonbi.py -c ~/Downloads/tonbi/config.json -d src -p flask -l python --exclude=sql_injection1 --exclude=sql_injection_var --exclude=sql_injection_raw
load config setting 
Traceback (most recent call last):
  File "/home/weongyo/Downloads/tonbi/tonbi.py", line 567, in <module>
    main()
  File "/home/weongyo/Downloads/tonbi/tonbi.py", line 509, in main
    load_config()
  File "/home/weongyo/Downloads/tonbi/tonbi.py", line 136, in load_config
    if(config_dic["source_directory"] ):
KeyError: 'source_directory'
```

**Comment by truefinder** [comment]
source_directory 
헉 컨피그화일에 저걸 빼 먹은거야 ? ㄷ ㄷ ㄷ ㄷ

**Comment by truefinder** [comment]
이번엔 왠지 진짜 고쳤을거 같은데 ....

https://github.com/truefinder/tonbi/commit/7bc3b33b470738862d54ca22a3225f382297d11f

**Comment by weongyo** [comment]
고쳐진 거 확인했습니다. ㄳㄳ
