### ISSUE TITLE
relative path 이슈

### ISSUE THREAD

**Issue by weongyo** [truefinder/tonbi#2]
설치 후 당연히 웹 소스가 있는 디렉토리에서 다음과 같이 실행을 시도함..

`$ python ~/Downloads/tonbi/tonby.py -d src/ -p flask -l python`

다음과 같이 실행 오류남.

```
check configuration
load platform ...
Traceback (most recent call last):
  File "/home/weongyo/Downloads/tonbi/tonbi.py", line 475, in <module>
    main()
  File "/home/weongyo/Downloads/tonbi/tonbi.py", line 460, in main
    yara_load_platform() 
  File "/home/weongyo/Downloads/tonbi/tonbi.py", line 139, in yara_load_platform
    with open( filename  ) as f : 
FileNotFoundError: [Errno 2] No such file or directory: './platform/flask.yar'
```

**Comment by truefinder** [comment]
https://github.com/truefinder/tonbi/commit/65e12d8149de9c1f7884edf9eebb2c0eb90894db

상대경로에 대한 수정 완료 ~
