### ISSUE TITLE
yara dependency 관련 문서화 이슈

### ISSUE THREAD

**Issue by weongyo** [truefinder/tonbi#4]
Ubuntu 에서는 libyara3 패키지를 설치를 해야 했음... 어딘가 문서화를 해놓아야 사용자들이 헷갈리지 않은 듯..

그리고 tonby.py 실행시 아래와 같이 뜸..  libyara.so 는 python-yara 패키지의 파일이었고, 결국 강제로 ln -s 명령으로 soft-link 를 걸어줬어야 했음... 당황했음..

```
$ python3 tonbi.py 
Failed to import '/usr/lib/libyara.so'
PATH = /bin:/usr/bin:/usr/X11R6/bin:/usr/local/bin:/home/weongyo/.local/bin;/usr/lib
Traceback (most recent call last):
  File "tonbi.py", line 6, in <module>
    import yara 
  File "/home/weongyo/.local/lib/python3.5/site-packages/yara/__init__.py", line 7, in <module>
    from yara.rules import compile
  File "/home/weongyo/.local/lib/python3.5/site-packages/yara/rules.py", line 17, in <module>
    from yara.libyara_wrapper import *
  File "/home/weongyo/.local/lib/python3.5/site-packages/yara/libyara_wrapper.py", line 315, in <module>
    libyaradll = cdll.LoadLibrary(library)
  File "/usr/lib/python3.5/ctypes/__init__.py", line 425, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python3.5/ctypes/__init__.py", line 347, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/lib/libyara.so: cannot open shared object file: No such file or directory
```

**Comment by truefinder** [comment]
https://github.com/truefinder/tonbi/commit/a2a9c9d2d357168dd03282681dfbb1e434d8b46d

우분투에서는 다이나믹 링킹이라니... 나는 mac 유저라서 ㄷ ㄷ ㄷ
